"""Host protection for the lifecycle and upgrade suites.

The sandbox PATH of recorder helpers (``_lifecycle_sandbox``) only governs
the processes a suite starts itself. Onebox resolves a bare program name
through PATH and then the fixed ``SAFE_PATH`` (``src/sys/exec.rs``), and
every daemon, oneshot and pre-start command it starts runs with a cleared
environment and ``PATH=SAFE_PATH`` (``Cmd::daemon_env``): the
``onebox-network`` oneshot, for one, runs ``onebox net-apply``, which would
call the host's real ``iptables``, ``nft`` and ``crontab``. Two layers keep
such an escape from changing the runner's or developer's host unnoticed:

* :func:`host_state` snapshots the host firewall (``iptables-save``,
  ``ip6tables-save``, ``nft list ruleset``) and root's crontab with the test
  process's own PATH; every sandbox takes one when it is created and fails
  its cleanup when the host differs (packet counters and the timestamps of
  ``iptables-save`` are ignored; a host whose firewall changes by itself
  while a suite runs, such as Docker starting containers, trips it too).
* :func:`seal` (root, Python 3.12+) moves the suite process into a private
  mount namespace and bind-mounts a *tripwire* directory over
  ``/usr/local/sbin``, the first ``SAFE_PATH`` entry: there every
  host-changing program name of the sandbox (``_lifecycle_fixtures.TRIPWIRE``)
  resolves first, is logged and exits 97 (the few read-only probes of
  ``_lifecycle_fixtures.TRIPWIRE_PROBES`` fail quietly instead and are not
  violations). Every child, including the daemons Onebox starts, inherits
  the namespace; the host never sees the mount.
"""
from __future__ import annotations

import functools
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
from typing import Sequence

import _lifecycle_fixtures as fx

HOST_PROBES = (("iptables-save",), ("ip6tables-save",), ("nft", "list", "ruleset"), ("crontab", "-l"))
# src/sys/exec.rs SAFE_PATH; its first entry is where the tripwire goes.
SAFE_PATH = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
SEAL_POINT = Path(SAFE_PATH.split(":")[0])
# Packet/byte counters (iptables-save "[pkts:bytes]", nft "counter packets N
# bytes M") and the iptables-save header/footer timestamps change by themselves.
_VOLATILE = re.compile(r"\[\d+:\d+\]|packets \d+ bytes \d+")
_STAMP = re.compile(r"^# (Generated by|Completed on) ")


class HostError(AssertionError):
    """The host was changed, or a process reached a host program."""


class SealUnavailable(Exception):
    """The host programs cannot be masked here (the reason is the message)."""


@functools.cache
def host_probes() -> tuple[tuple[str, ...], ...]:
    """HOST_PROBES with absolute programs, resolved once with this process's
    PATH (before :func:`seal` masks ``/usr/local/sbin``); missing tools are
    left out."""
    resolved = []
    for program, *args in HOST_PROBES:
        path = shutil.which(program)
        if path and Path(path).parent != SEAL_POINT:
            resolved.append((path, *args))
    return tuple(resolved)


def host_state(probes: Sequence[Sequence[str]]) -> dict[str, str]:
    """Probe command → its exit status and normalized standard output."""
    state = {}
    for argv in probes:
        proc = subprocess.run(list(argv), capture_output=True, text=True, timeout=60,
                              stdin=subprocess.DEVNULL)
        lines = [_VOLATILE.sub("", line) for line in proc.stdout.splitlines()
                 if not _STAMP.match(line)]
        state[" ".join(argv)] = "\n".join([f"exit {proc.returncode}", *lines])
    return state


def state_changes(before: dict[str, str], after: dict[str, str]) -> list[str]:
    """One description per probe whose result changed."""
    return [f"{probe}:\n--- before\n{before.get(probe)}\n--- after\n{after.get(probe)}"
            for probe in sorted(set(before) | set(after)) if before.get(probe) != after.get(probe)]


class Tripwire:
    """The calls log of a :func:`seal`."""

    def __init__(self, log: Path):
        self.log = log

    def calls(self) -> list[dict]:
        """Every call a tripwire took, read-only probes included."""
        if not self.log.exists():
            return []
        return [json.loads(line) for line in self.log.read_text().splitlines() if line]


def write_tripwire(directory: Path) -> Tripwire:
    """Create DIRECTORY with one tripwire per TRIPWIRE name."""
    directory.mkdir(mode=0o755)
    tripwire = Tripwire(directory.parent / f"{directory.name}-calls.jsonl")
    fx.install_tripwires(directory, tripwire.log)
    return tripwire


def seal(work: Path) -> Tripwire:
    """Mask the host programs for this process and its children (module
    docs). Raises SealUnavailable when this host cannot do it."""
    if os.geteuid() != 0:
        raise SealUnavailable("masking host programs requires root")
    if not hasattr(os, "unshare"):
        raise SealUnavailable("masking host programs requires Python 3.12 or later")
    if not SEAL_POINT.is_dir() or SEAL_POINT.is_symlink():
        raise SealUnavailable(f"{SEAL_POINT} is not a plain directory")
    if Path(sys.executable).resolve().parent == SEAL_POINT:
        raise SealUnavailable(f"the Python interpreter lives in {SEAL_POINT}")
    mount = shutil.which("mount", path="/usr/bin:/bin")
    if not mount:
        raise SealUnavailable("mount(8) not found")
    host_probes()  # resolved before the real tools are masked
    tripwire = write_tripwire(work / "tripwire")
    try:
        os.unshare(os.CLONE_NEWNS)
    except OSError as error:
        raise SealUnavailable(f"no private mount namespace: {error}") from error
    # Without private propagation the bind mount would reach the host.
    for argv in ([mount, "--make-rprivate", "/"],
                 [mount, "--bind", str(work / "tripwire"), str(SEAL_POINT)]):
        proc = subprocess.run(argv, capture_output=True, text=True, stdin=subprocess.DEVNULL)
        if proc.returncode:
            raise SealUnavailable(f"{' '.join(argv)}: {proc.stderr.strip()}")
    check_seal(tripwire)
    return tripwire


def check_seal(tripwire: Tripwire, path: str = SAFE_PATH) -> None:
    """A child with Onebox's daemon environment (cleared, PATH=PATH) must
    reach the tripwire, not the host's iptables; the check's own call is
    then forgotten."""
    try:
        proc = subprocess.run(["iptables", "-S"], env={"PATH": path}, capture_output=True,
                              text=True, stdin=subprocess.DEVNULL, timeout=30)
        code: object = proc.returncode
    except OSError as error:
        code = error
    calls = tripwire.calls()
    if code != fx.BLOCKED_EXIT or [c["argv"] for c in calls] != [["iptables", "-S"]]:
        raise HostError(f"the tripwire over {SEAL_POINT} is not in effect: {code!r}, calls {calls}")
    tripwire.log.unlink()
