//! Lifecycle tests on the fake host (systemd, crontab, release, DNS,
//! nginx and iptables faked; the real openssl creates the private CA).

use super::*;
use crate::domain::fixtures::config;
use crate::domain::protocol::{Core, Protocol};
use crate::frp::ca::ControlFiles;
use crate::frp::model::Mode;
use crate::frp::render::server_toml;
use crate::frp::testing::{fake_frps, tcp_state, web_state, FakeHost};
use crate::frp::txn::ROLLED_BACK;
use crate::host::service::unit_file;
use crate::state::StateStore;
use std::fs;
use std::os::unix::fs::PermissionsExt;

fn change(reason: &'static str) -> Change {
    Change {
        reason,
        ..Change::default()
    }
}

/// A fresh tcp install (token generated by the apply).
fn install_tcp(h: &FakeHost) -> FrpState {
    let mut state = tcp_state();
    state.token.clear();
    apply(&h.runtime(), state, change("安装")).unwrap();
    model::load(&h.ctx.paths).unwrap().unwrap()
}

fn mode_of(path: &std::path::Path) -> u32 {
    fs::metadata(path).unwrap().permissions().mode() & 0o777
}

fn curls(h: &FakeHost) -> usize {
    h.history().iter().filter(|c| c.starts_with("curl")).count()
}

#[test]
fn tcp_install_deploys_everything_and_commits() {
    let Some(h) = FakeHost::new() else { return };
    let saved = install_tcp(&h);
    let paths = &h.ctx.paths;
    assert_eq!(saved.token.len(), 64);
    assert_eq!(saved.version, "0.71.0");
    assert_eq!(
        fs::read(paths.frp_bin.join("frps")).unwrap(),
        fake_frps("0.71.0")
    );
    assert_eq!(mode_of(&paths.frp_bin.join("frps")), 0o755);
    assert_eq!(
        fs::read_to_string(paths.frp_root.join("frps.toml")).unwrap(),
        server_toml(&saved, &paths.frp_root)
    );
    let files = ControlFiles::new(&paths.frp_root);
    for file in [
        files.ca(),
        files.ca_key(),
        files.cert(),
        files.key(),
        paths.frp_root.join("state.json"),
        paths.frp_root.join("frps.toml"),
    ] {
        assert_eq!(mode_of(&file), 0o600, "{}", file.display());
    }
    for dir in [&paths.frp_root, &paths.frp_bin, &paths.frp_web] {
        assert!(dir.join(".managed").is_file());
        assert_eq!(mode_of(dir), 0o700);
    }
    assert!(paths.frp_root.join("services/onebox-frps.json").is_file());
    assert!(unit_file(paths, FRPS).is_file());
    assert!(!unit_file(paths, FRP_WEB).exists());
    assert!(h.running(FRPS) && h.enabled(FRPS));
    let renew_tail = format!(
        " frps renew --cron >>'{}' 2>&1 # onebox:frp-renew",
        paths.frp_log.join("renew.log").display()
    );
    let tab = h.crontab();
    assert!(tab.starts_with("17 3 * * * PATH="), "{tab}");
    assert!(tab.trim_end().ends_with(&renew_tail), "{tab}");
    assert!(!journal::exists(paths));
    let ledger = fs::read_to_string(paths.frp_root.join("firewall-v2.json")).unwrap();
    assert!(ledger.contains("\"port\": 7000") && ledger.contains("\"port\": 20000"));
    assert!(h.ui.prompts().is_empty(), "apply never asks");
}

#[test]
fn a_failed_fresh_install_leaves_nothing_behind() {
    let Some(h) = FakeHost::new() else { return };
    h.set_healthy(false);
    let mut state = tcp_state();
    state.token.clear();
    let err = apply(&h.runtime(), state.clone(), change("安装")).unwrap_err();
    assert_eq!(
        err.to_string(),
        format!("FRP 启动或私有 CA / TLS 健康检查失败{ROLLED_BACK}")
    );
    let paths = &h.ctx.paths;
    for dir in [&paths.frp_root, &paths.frp_bin, &paths.frp_web] {
        assert!(!dir.exists(), "{}", dir.display());
    }
    assert!(!unit_file(paths, FRPS).exists());
    assert!(!h.running(FRPS) && !h.enabled(FRPS));
    assert!(!h.crontab().contains("frp"));
    assert!(!journal::exists(paths));
    // The next attempt is not refused as "not managed".
    h.set_healthy(true);
    apply(&h.runtime(), state, change("安装")).unwrap();
}

#[test]
fn a_failed_change_restores_token_binary_and_private_ca() {
    let Some(h) = FakeHost::new() else { return };
    let before = install_tcp(&h);
    let paths = &h.ctx.paths;
    let ca_key = fs::read(paths.frp_root.join("ca-key.pem")).unwrap();
    let crontab = h.crontab();
    h.set_healthy(false);
    let err = apply(
        &h.runtime(),
        before.clone(),
        Change {
            rotate: true,
            reason: "轮换 token",
            ..Change::default()
        },
    )
    .unwrap_err();
    assert!(err.to_string().ends_with(ROLLED_BACK), "{err}");
    assert_eq!(model::load(paths).unwrap().unwrap(), before);
    assert_eq!(fs::read(paths.frp_root.join("ca-key.pem")).unwrap(), ca_key);
    assert_eq!(
        fs::read(paths.frp_bin.join("frps")).unwrap(),
        fake_frps("0.71.0")
    );
    assert!(h.running(FRPS) && h.enabled(FRPS), "restarted as before");
    assert_eq!(h.crontab(), crontab);
    assert!(!journal::exists(paths));
}

#[test]
fn configure_with_the_installed_version_needs_no_network() {
    let Some(h) = FakeHost::new() else { return };
    let mut state = install_tcp(&h);
    h.exec.clear_history();
    state.bind_port = 7001;
    apply(&h.runtime(), state, change("配置")).unwrap();
    assert_eq!(curls(&h), 0, "{:?}", h.history());
    assert_eq!(model::load(&h.ctx.paths).unwrap().unwrap().bind_port, 7001);
}

#[test]
fn update_to_the_running_version_changes_nothing() {
    let Some(h) = FakeHost::new() else { return };
    let state = install_tcp(&h);
    h.exec.clear_history();
    let mut latest = state.clone();
    latest.version = "latest".into();
    let update = Change {
        reason: "更新",
        skip_unchanged: true,
        ..Change::default()
    };
    apply(&h.runtime(), latest, update).unwrap();
    assert!(!h.history().iter().any(|c| c.starts_with("systemctl stop")));
    assert_eq!(model::load(&h.ctx.paths).unwrap().unwrap(), state);
    assert!(h.running(FRPS));
}

#[test]
fn crashed_transactions_block_net_apply_until_recovered() {
    let Some(h) = FakeHost::new() else { return };
    let original = install_tcp(&h);
    let rt = h.runtime();
    let paths = &h.ctx.paths;
    {
        let lock = rt.lock().unwrap();
        let mut txn = Txn::begin(&rt, &lock, "测试", &journal::targets(paths)).unwrap();
        txn.phase(Phase::WriteFiles).unwrap();
        let mut changed = original.clone();
        changed.token = "f".repeat(64);
        model::save(paths, &changed).unwrap();
        fs::write(paths.frp_bin.join("frps"), fake_frps("0.72.0")).unwrap();
        rt.services().stop(FRPS).unwrap();
        // The process dies here: no commit, no rollback.
    }
    assert!(journal::exists(paths));
    assert_eq!(net_apply(&h.ctx).unwrap_err().to_string(), journal::PENDING);
    {
        // While an FRP operation holds the lock, the hook proceeds.
        let _held = rt.lock().unwrap();
        net_apply(&h.ctx).unwrap();
    }
    let lock = rt.lock().unwrap();
    assert!(recover_locked(&rt, &lock).unwrap());
    assert_eq!(model::load(paths).unwrap().unwrap(), original);
    assert_eq!(
        fs::read(paths.frp_bin.join("frps")).unwrap(),
        fake_frps("0.71.0")
    );
    assert!(h.running(FRPS));
    assert!(!journal::exists(paths));
    drop(lock);
    net_apply(&h.ctx).unwrap();
    assert!(!recover_locked(&rt, &rt.lock().unwrap()).unwrap());
}

#[test]
fn every_mutation_recovers_first() {
    let Some(h) = FakeHost::new() else { return };
    let original = install_tcp(&h);
    let rt = h.runtime();
    let paths = &h.ctx.paths;
    {
        let lock = rt.lock().unwrap();
        let _txn = Txn::begin(&rt, &lock, "测试", &journal::targets(paths)).unwrap();
        let mut changed = original.clone();
        changed.bind_port = 7009;
        model::save(paths, &changed).unwrap();
    }
    let lock = rt.lock().unwrap();
    service(&rt, &lock, ServiceAction::Restart).unwrap();
    assert_eq!(model::load(paths).unwrap().unwrap(), original);
    assert!(!journal::exists(paths));
}

#[test]
fn renew_restarts_frps_only_when_the_control_certificate_changed() {
    let Some(h) = FakeHost::new() else { return };
    install_tcp(&h);
    let rt = h.runtime();
    let lock = rt.lock().unwrap();
    h.exec.clear_history();
    renew(&rt, &lock, true).unwrap();
    let restarted = |h: &FakeHost| {
        h.history()
            .iter()
            .any(|c| c == "systemctl restart onebox-frps")
    };
    assert!(!restarted(&h));
    fs::remove_file(ControlFiles::new(&h.ctx.paths.frp_root).cert()).unwrap();
    renew(&rt, &lock, true).unwrap();
    assert!(restarted(&h));
    assert!(!journal::exists(&h.ctx.paths));
}

#[test]
fn service_control() {
    let Some(h) = FakeHost::new() else { return };
    install_tcp(&h);
    let rt = h.runtime();
    let lock = rt.lock().unwrap();
    service(&rt, &lock, ServiceAction::Stop).unwrap();
    assert!(!h.running(FRPS) && h.enabled(FRPS));
    service(&rt, &lock, ServiceAction::Start).unwrap();
    assert!(h.running(FRPS));
    h.set_healthy(false);
    let err = service(&rt, &lock, ServiceAction::Restart).unwrap_err();
    assert_eq!(err.to_string(), "FRP 启动或私有 CA / TLS 健康检查失败");
}

#[test]
fn uninstall_removes_everything_but_foreign_cron_lines() {
    let Some(h) = FakeHost::new() else { return };
    h.set_crontab("0 1 * * * /usr/bin/true\n");
    install_tcp(&h);
    let rt = h.runtime();
    let lock = rt.lock().unwrap();
    uninstall(&rt, &lock).unwrap();
    let paths = &h.ctx.paths;
    for dir in [
        &paths.frp_root,
        &paths.frp_bin,
        &paths.frp_web,
        &paths.frp_log,
        &paths.frp_run,
    ] {
        assert!(!dir.exists(), "{}", dir.display());
    }
    assert!(!unit_file(paths, FRPS).exists());
    assert!(!h.running(FRPS) && !h.enabled(FRPS));
    assert_eq!(h.crontab(), "0 1 * * * /usr/bin/true\n");
    assert!(!journal::exists(paths));
    assert_eq!(
        uninstall(&rt, &lock).unwrap_err().to_string(),
        model::NOT_INSTALLED
    );
}

#[test]
fn v2_cron_lines_are_rewritten_in_place() {
    let Some(h) = FakeHost::new() else { return };
    h.set_crontab(
        "MAILTO=root\n\
         17 3 * * * env ONEBOX_DIR='/etc/onebox' '/usr/local/bin/onebox' frps renew --cron >>'/var/log/onebox-frp/renew.log' 2>&1 # onebox-frps-renew\n\
         @reboot env ONEBOX_DIR='/etc/onebox' '/usr/local/bin/onebox' frps start >>'/var/log/onebox-frp/boot.log' 2>&1 # onebox-frps-boot\n\
         0 1 * * * /usr/bin/true\n",
    );
    install_tcp(&h);
    let tab = h.crontab();
    let lines: Vec<&str> = tab.lines().collect();
    assert_eq!(lines.len(), 3, "{tab}");
    assert_eq!(lines[0], "MAILTO=root");
    assert!(lines[1].ends_with("# onebox:frp-renew"));
    assert_eq!(lines[2], "0 1 * * * /usr/bin/true");
}

#[test]
fn unmanaged_directories_and_units_are_never_adopted() {
    let Some(h) = FakeHost::new() else { return };
    let paths = &h.ctx.paths;
    fs::create_dir_all(&paths.frp_root).unwrap();
    let err = apply(&h.runtime(), tcp_state(), change("安装")).unwrap_err();
    assert_eq!(
        err.to_string(),
        format!("拒绝接管非本程序管理的目录: {}", paths.frp_root.display())
    );
    fs::remove_dir(&paths.frp_root).unwrap();
    fs::create_dir_all(&paths.systemd).unwrap();
    fs::write(unit_file(paths, FRPS), "[Service]\n").unwrap();
    let err = apply(&h.runtime(), tcp_state(), change("安装")).unwrap_err();
    assert_eq!(
        err.to_string(),
        format!("拒绝接管现有服务: {}", unit_file(paths, FRPS).display())
    );
    assert!(!journal::exists(paths));
    assert!(!paths.frp_root.exists());
}

#[test]
fn node_port_conflicts_roll_back() {
    let Some(h) = FakeHost::new() else { return };
    let node = config(&[(Protocol::Hysteria2, 20005, Core::Singbox)]);
    StateStore::save(&h.ctx, &node).unwrap();
    let err = apply(&h.runtime(), tcp_state(), change("安装")).unwrap_err();
    assert_eq!(
        err.to_string(),
        format!("FRP 20000-20010/both 与已有代理或网站 20005-20005/udp 冲突{ROLLED_BACK}")
    );
    assert!(!h.ctx.paths.frp_root.exists());
}

/// A self-signed pair for `app.example.com` (a custom certificate).
fn custom_pair(h: &FakeHost) -> (String, String) {
    let dir = h.dir.join("custom");
    fs::create_dir_all(&dir).unwrap();
    let (cert, key) = (dir.join("cert.pem"), dir.join("key.pem"));
    let path = |p: &std::path::Path| p.to_string_lossy().into_owned();
    let cmd = Cmd::new("openssl").args([
        "req",
        "-x509",
        "-newkey",
        "ec",
        "-pkeyopt",
        "ec_paramgen_curve:prime256v1",
        "-nodes",
        "-days",
        "365",
        "-subj",
        "/CN=app.example.com",
        "-addext",
        "subjectAltName=DNS:app.example.com",
        "-addext",
        "extendedKeyUsage=serverAuth",
        "-keyout",
        &path(&key),
        "-out",
        &path(&cert),
    ]);
    h.ctx.check(&cmd).unwrap();
    (path(&cert), path(&key))
}

#[test]
fn web_mode_with_a_custom_certificate_then_back_to_tcp() {
    let Some(h) = FakeHost::new() else { return };
    let (cert, key) = custom_pair(&h);
    let mut state = web_state(WebTls::Custom { cert, key });
    state.token.clear();
    apply(&h.runtime(), state, change("安装")).unwrap();
    let paths = &h.ctx.paths;
    let conf = fs::read_to_string(paths.frp_root.join("nginx.conf")).unwrap();
    assert!(conf.starts_with("# Managed by Onebox FRP\nuser www-data www-data;\n"));
    assert!(conf.contains("server_name app.example.com; ssl_certificate"));
    assert!(paths.frp_root.join("web-tls/cert.pem").is_file());
    assert!(paths
        .frp_root
        .join("services/onebox-frp-web.json")
        .is_file());
    assert!(h.running(FRP_WEB) && h.enabled(FRP_WEB));
    assert_eq!(mode_of(&paths.frp_web), 0o755);
    assert_eq!(
        mode_of(&paths.frp_web.join("www/.well-known/acme-challenge")),
        0o755
    );

    let installed = model::load(paths).unwrap().unwrap();
    let mut tcp = installed.clone();
    tcp.mode = tcp_state().mode;
    apply(&h.runtime(), tcp, change("配置")).unwrap();
    assert!(!h.running(FRP_WEB) && !h.enabled(FRP_WEB));
    assert!(!unit_file(paths, FRP_WEB).exists());
    assert!(!paths.frp_root.join("nginx.conf").exists());
    assert!(paths.frp_root.join("web-tls/cert.pem").is_file(), "kept");
    assert!(matches!(
        model::load(paths).unwrap().unwrap().mode,
        Mode::Tcp { .. }
    ));
}
