//! The editable form of an FRP configuration: a flat [`Draft`] that the
//! command-line flags (spec H §2.4) and the wizard (H §2.5) change field by
//! field, exactly like v2's flat `Config`, and that is then turned into the
//! typed [`FrpState`] and validated once.
//!
//! The flat form keeps the settings of the other mode while the user edits
//! (`--mode tcp --allow-ports …` on a web state, or switching modes in the
//! wizard); only the fields of the chosen mode end up in the state.
//!
//! Changes from v2:
//! - modes and certificate methods are typed ([`ModeKind`], [`TlsKind`]);
//!   bad values fail where they are parsed, with v2's messages;
//! - option values are parsed with Chinese messages instead of raw
//!   `ParseIntError` text (H-8.1#16), a flag is never taken as the value of
//!   another option (the CLI parser refuses it, H-8.1#21);
//! - options that do not apply to the chosen mode are reported as ignored
//!   instead of being stored silently;
//! - relative `--cert`/`--key` paths are resolved against the current
//!   directory when they are given, so a renewal run by cron from `/` still
//!   finds them (v2 stored them verbatim and resolved them at apply time);
//! - a new configuration must name DNS domains (H-8.1#15), see
//!   [`FrpState::validate_change`].

use super::model::{
    AppDomain, BindAddr, FrpState, Mode, WebSettings, WebTls, DEFAULT_BIND_PORT,
    DEFAULT_HTTPS_PORT, DEFAULT_HTTP_PORT, DEFAULT_RANGE, DEFAULT_REDIRECT_PORT, SCHEMA,
};
use crate::cli::args::Matches;
use crate::domain::config::PortRange;
use crate::domain::defaults::FRP_VERSION;
use crate::error::{Error, Result};
use std::path::{Component, Path, PathBuf};

/// `web` (HTTPS applications behind nginx) or `tcp` (public port range).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ModeKind {
    Web,
    Tcp,
}

impl ModeKind {
    pub fn parse(value: &str) -> Result<ModeKind> {
        match value {
            "web" => Ok(ModeKind::Web),
            "tcp" => Ok(ModeKind::Tcp),
            _ => Err(Error::msg("FRP 模式应为 web 或 tcp")),
        }
    }

    pub fn id(self) -> &'static str {
        match self {
            ModeKind::Web => "web",
            ModeKind::Tcp => "tcp",
        }
    }
}

/// How the web-mode certificate is obtained (`http`, `cf`, `custom`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TlsKind {
    Http01,
    Cloudflare,
    Custom,
}

impl TlsKind {
    pub fn parse(value: &str) -> Result<TlsKind> {
        match value {
            "http" => Ok(TlsKind::Http01),
            "cf" => Ok(TlsKind::Cloudflare),
            "custom" => Ok(TlsKind::Custom),
            _ => Err(Error::msg("网站证书方式应为 http、cf 或 custom")),
        }
    }

    fn of(tls: &WebTls) -> TlsKind {
        match tls {
            WebTls::Http01 => TlsKind::Http01,
            WebTls::Cloudflare => TlsKind::Cloudflare,
            WebTls::Custom { .. } => TlsKind::Custom,
        }
    }
}

/// Every FRP setting as one flat, editable record (v2's `Config` shape).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Draft {
    pub mode: ModeKind,
    pub domain: String,
    pub bind_addr: BindAddr,
    pub bind_port: u16,
    pub http_port: u16,
    pub https_port: u16,
    pub redirect_port: u16,
    /// Single application domain; empty when a wildcard root is used.
    pub web_domain: String,
    /// Wildcard root (`*.{root}`); empty for a single domain.
    pub subdomain_host: String,
    pub range: PortRange,
    pub tls: TlsKind,
    pub cert: String,
    pub key: String,
    /// `latest` or `0.x.y`.
    pub version: String,
    /// Empty before the first install (generated by the apply).
    pub token: String,
}

impl Draft {
    /// v2's defaults for a host without FRP: web mode, HTTP-01, ports
    /// 7000/7080/443/80, range 20000–20100, frp 0.71.0, no domains yet.
    pub fn fresh(ipv6: bool) -> Draft {
        Draft {
            mode: ModeKind::Web,
            domain: String::new(),
            bind_addr: BindAddr::default_for(ipv6),
            bind_port: DEFAULT_BIND_PORT,
            http_port: DEFAULT_HTTP_PORT,
            https_port: DEFAULT_HTTPS_PORT,
            redirect_port: DEFAULT_REDIRECT_PORT,
            web_domain: String::new(),
            subdomain_host: String::new(),
            range: DEFAULT_RANGE,
            tls: TlsKind::Http01,
            cert: String::new(),
            key: String::new(),
            version: FRP_VERSION.to_owned(),
            token: String::new(),
        }
    }

    /// The editable form of a stored state (the other mode's fields get
    /// the defaults).
    pub fn of(state: &FrpState) -> Draft {
        let mut draft = Draft {
            domain: state.domain.clone(),
            bind_addr: state.bind_addr,
            bind_port: state.bind_port,
            version: state.version.clone(),
            token: state.token.clone(),
            ..Draft::fresh(false)
        };
        match &state.mode {
            Mode::Tcp { range } => {
                draft.mode = ModeKind::Tcp;
                draft.range = *range;
            }
            Mode::Web(web) => {
                draft.mode = ModeKind::Web;
                draft.http_port = web.http_port;
                draft.https_port = web.https_port;
                draft.redirect_port = web.redirect_port;
                match &web.app {
                    AppDomain::Single { domain } => draft.web_domain = domain.clone(),
                    AppDomain::Wildcard { root } => draft.subdomain_host = root.clone(),
                }
                draft.tls = TlsKind::of(&web.tls);
                if let WebTls::Custom { cert, key } = &web.tls {
                    draft.cert = cert.clone();
                    draft.key = key.clone();
                }
            }
        }
        draft
    }

    /// The typed state (not yet validated, see [`finish`]).
    pub fn build(&self) -> Result<FrpState> {
        let mode = match self.mode {
            ModeKind::Tcp => Mode::Tcp { range: self.range },
            ModeKind::Web => Mode::Web(WebSettings {
                http_port: self.http_port,
                https_port: self.https_port,
                redirect_port: self.redirect_port,
                app: self.app()?,
                tls: match self.tls {
                    TlsKind::Http01 => WebTls::Http01,
                    TlsKind::Cloudflare => WebTls::Cloudflare,
                    TlsKind::Custom => WebTls::Custom {
                        cert: self.cert.clone(),
                        key: self.key.clone(),
                    },
                },
            }),
        };
        Ok(FrpState {
            schema: SCHEMA,
            domain: self.domain.clone(),
            bind_addr: self.bind_addr,
            bind_port: self.bind_port,
            token: self.token.clone(),
            version: self.version.clone(),
            mode,
        })
    }

    fn app(&self) -> Result<AppDomain> {
        match (self.web_domain.as_str(), self.subdomain_host.as_str()) {
            (domain, "") => Ok(AppDomain::Single {
                domain: domain.to_owned(),
            }),
            ("", root) => Ok(AppDomain::Wildcard {
                root: root.to_owned(),
            }),
            _ => Err(Error::msg("应用域名与泛域名根不能并用")),
        }
    }

    pub fn is_web(&self) -> bool {
        self.mode == ModeKind::Web
    }

    pub fn wildcard(&self) -> bool {
        !self.subdomain_host.is_empty()
    }
}

/// The validated state of `draft`: a first install may lack the token
/// ([`FrpState::validate_draft`]); a change of an installed state keeps
/// every v2-era value it does not touch ([`FrpState::validate_change`]).
pub fn finish(draft: &Draft, previous: Option<&FrpState>) -> Result<FrpState> {
    let state = draft.build()?;
    match previous {
        None => state.validate_draft()?,
        Some(previous) => state.validate_change(Some(previous))?,
    }
    Ok(state)
}

/// The configuration options of `frps install|configure|plan` (H §2.4),
/// each `None` when not given.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Flags {
    pub mode: Option<ModeKind>,
    pub domain: Option<String>,
    pub bind_port: Option<u16>,
    pub http_port: Option<u16>,
    pub https_port: Option<u16>,
    pub redirect_port: Option<u16>,
    pub web_domain: Option<String>,
    pub subdomain_host: Option<String>,
    pub range: Option<PortRange>,
    pub tls: Option<TlsKind>,
    pub cert: Option<String>,
    pub key: Option<String>,
    pub version: Option<String>,
}

/// Long names of every configuration option (declared by the CLI spec).
pub const OPTION_NAMES: [&str; 13] = [
    "mode",
    "domain",
    "port",
    "http-port",
    "https-port",
    "redirect-port",
    "web-domain",
    "subdomain-host",
    "allow-ports",
    "tls",
    "cert",
    "key",
    "version",
];

/// The last value of a (repeatable) option: v2 let a repeated flag win.
fn last<'a>(m: &'a Matches, long: &str) -> Option<&'a str> {
    m.values(long).last().map(String::as_str)
}

fn port(m: &Matches, long: &str) -> Result<Option<u16>> {
    last(m, long)
        .map(|v| {
            v.parse::<u16>()
                .map_err(|_| Error::msg(format!("--{long} 的值无效: {v}")))
        })
        .transpose()
}

/// `A-B` with two port numbers (H §2.4); the range rules are checked with
/// the whole state.
pub fn parse_allow_ports(value: &str) -> Result<PortRange> {
    let bad = || Error::msg("--allow-ports 格式为 20000-20100");
    let (a, b) = value.split_once('-').ok_or_else(bad)?;
    let start = a.trim().parse::<u16>().map_err(|_| bad())?;
    let end = b.trim().parse::<u16>().map_err(|_| bad())?;
    Ok(PortRange { start, end })
}

/// A version argument: a leading `v` is dropped (`v0.71.0`, `latest`).
pub fn normalize_version(value: &str) -> String {
    value.trim_start_matches('v').to_owned()
}

/// `path` made absolute against `cwd` (no `..` allowed).
pub fn absolute_path(path: &str, cwd: &Path) -> Result<String> {
    let p = Path::new(path);
    ensure!(
        !p.components().any(|c| c == Component::ParentDir),
        "证书路径不能包含 ..: {path}"
    );
    let full: PathBuf = if p.is_absolute() {
        p.to_path_buf()
    } else {
        cwd.join(p)
    };
    Ok(full.to_string_lossy().into_owned())
}

impl Flags {
    /// Read the options of a parsed command line; relative certificate
    /// paths are resolved against `cwd`.
    pub fn from_matches(m: &Matches, cwd: &Path) -> Result<Flags> {
        let web = last(m, "web-domain");
        let sub = last(m, "subdomain-host");
        ensure!(
            web.is_none() || sub.is_none(),
            "--web-domain 与 --subdomain-host 不能同时使用"
        );
        let lower = |v: Option<&str>| v.map(str::to_ascii_lowercase);
        let path = |long: &str| -> Result<Option<String>> {
            last(m, long).map(|v| absolute_path(v, cwd)).transpose()
        };
        Ok(Flags {
            mode: last(m, "mode").map(ModeKind::parse).transpose()?,
            domain: lower(last(m, "domain")),
            bind_port: port(m, "port")?,
            http_port: port(m, "http-port")?,
            https_port: port(m, "https-port")?,
            redirect_port: port(m, "redirect-port")?,
            web_domain: lower(web),
            subdomain_host: lower(sub),
            range: last(m, "allow-ports").map(parse_allow_ports).transpose()?,
            tls: last(m, "tls").map(TlsKind::parse).transpose()?,
            cert: path("cert")?,
            key: path("key")?,
            version: last(m, "version").map(normalize_version),
        })
    }

    pub fn is_empty(&self) -> bool {
        *self == Flags::default()
    }

    /// Set the given fields on `draft` (a domain flag clears the other
    /// kind of application name, as in v2).
    pub fn apply(&self, draft: &mut Draft) {
        let set = |slot: &mut String, value: &Option<String>| {
            if let Some(v) = value {
                slot.clone_from(v);
            }
        };
        let set_port = |slot: &mut u16, value: Option<u16>| {
            if let Some(v) = value {
                *slot = v;
            }
        };
        if let Some(mode) = self.mode {
            draft.mode = mode;
        }
        set(&mut draft.domain, &self.domain);
        set_port(&mut draft.bind_port, self.bind_port);
        set_port(&mut draft.http_port, self.http_port);
        set_port(&mut draft.https_port, self.https_port);
        set_port(&mut draft.redirect_port, self.redirect_port);
        if let Some(domain) = &self.web_domain {
            draft.web_domain.clone_from(domain);
            draft.subdomain_host.clear();
        }
        if let Some(root) = &self.subdomain_host {
            draft.subdomain_host.clone_from(root);
            draft.web_domain.clear();
        }
        if let Some(range) = self.range {
            draft.range = range;
        }
        if let Some(tls) = self.tls {
            draft.tls = tls;
        }
        set(&mut draft.cert, &self.cert);
        set(&mut draft.key, &self.key);
        set(&mut draft.version, &self.version);
    }

    /// Options given that the final mode does not use (`--allow-ports` in
    /// web mode, web options in tcp mode), for a notice.
    pub fn ignored(&self, mode: ModeKind) -> Vec<&'static str> {
        let web_only = [
            ("--http-port", self.http_port.is_some()),
            ("--https-port", self.https_port.is_some()),
            ("--redirect-port", self.redirect_port.is_some()),
            ("--web-domain", self.web_domain.is_some()),
            ("--subdomain-host", self.subdomain_host.is_some()),
            ("--tls", self.tls.is_some()),
            ("--cert", self.cert.is_some()),
            ("--key", self.key.is_some()),
        ];
        match mode {
            ModeKind::Web => [("--allow-ports", self.range.is_some())]
                .into_iter()
                .filter(|(_, given)| *given)
                .map(|(name, _)| name)
                .collect(),
            ModeKind::Tcp => web_only
                .into_iter()
                .filter(|(_, given)| *given)
                .map(|(name, _)| name)
                .collect(),
        }
    }
}

#[cfg(test)]
mod tests;
